/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_HelloWorld_create(JNIEnv* env);

JNIEXPORT int JNICALL Java_HelloWorld_get_1ok(JNIEnv* env);

JNIEXPORT int JNICALL Java_HelloWorld_sum(JNIEnv* env, jlong obj, jint a, jint b);

JNIEXPORT void JNICALL Java_HelloWorld_destroy(JNIEnv* env, jlong obj);

JNIEXPORT void JNICALL Java_HelloWorld_print(JNIEnv* env, jobject obj);

JNIEXPORT void JNICALL Java_Widget_print(JNIEnv* env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
